repos:
  -
    repo: local
    hooks:
      -
        id: isort
        name: 'Run isort import sorter/organizer'
        entry: 'env/bin/isort'
        language: system
        types:
          - python
      -
        id: black
        name: 'Run black code formatter'
        entry: 'env/bin/black'
        language: system
        types:
          - python
  -
    repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v1.2.3
    hooks:
      -
        id: flake8
