# This file documents the configuration file that should be passed to demos.
# For documentation on all these fields, see the `config_util` module.

### Summary
summary_of_run: |
  No system influence. Here we show that the algo can segment even when changes are hard to perceive visually.

### Data Generation 
L_true: 6 # currently must be even multiple of K 
K_true: 2 
D_true: 3 # state_dim 
N : 4 # obs_dim 
T : 200
seed : 99
fixed_regime_run_length_for_entities : 0
# `system_influence_scalar` gives the strength of influence of system on observed time series.
#  For no influence set to 0.
# This is not used if `fixed_regime_run_length_for_entities` = True. 
system_influence_scalar : 0.0
alpha : 1.0 # Dirichlet parameter for symmetric Dirichlet on rows on t.p.m for regimes ....
kappa : 0.0 # ...with symmetry-breaking increment to prior to encourage self-transitions. 

### Inference 
num_iters_laplace_em : 100
smart_initialize : True 
num_init_ar_hmms : 1

