# This file documents the configuration file that should be passed to demos.
# For documentation on all these fields, see the `config_util` module.

### Summary
summary_of_run: |
  System influence. 4 system-level regimes, 4 entity-level regimes.
  Currently set equal because it simplifies tracking entity responsiveness
  to system influence. 

### Data Generation 
L_true: 4 # currently must be even multiple of K 
K_true: 4 
D_true: 3 # state_dim 
N : 4 # obs_dim 
T : 200
seed : 25
fixed_run_length_for_entity_level_regimes : 0 
fixed_run_length_for_system_level_regimes : 5
# `system_influence_scalar` gives the strength of influence of system on observed time series.
#  For no influence set to 0.
# This is not used if `fixed_run_length_for_entity_level_regimes` = True. 
system_influence_scalar : 100.0
alpha : 1.0 # Dirichlet parameter for symmetric Dirichlet on rows on t.p.m for regimes ....
kappa : 0.0 # ...with symmetry-breaking increment to prior to encourage self-transitions. 

### Inference 
num_iters_laplace_em : 100
smart_initialize : True 
num_init_ar_hmms : 1
