# This file documents the configuration file that should be passed to demos.
# For documentation on all these fields, see the `config_util` module.

### Summary
summary_of_run: | 
  System influence. Here we have four entity-level regimes.  When there are quick cycles of system-driven inference,
  we get poor inference for regime segmentations, but we still get good inference for continuous 
  states AND observations.    Note: perhaps the sticky transitions "prior" is at fault here.


### Data Generation 
L_true: 8 # currently must be even multiple of K 
K_true: 4 
D_true: 3 # state_dim 
N : 4 # obs_dim 
T : 200
seed : 1
fixed_run_length_for_entity_level_regimes : 0
# `system_influence_scalar` gives the strength of influence of system on observed time series.
#  For no influence set to 0.
# This is not used if `fixed_run_length_for_entity_level_regimes` = True. 
fixed_run_length_for_system_level_regimes : 1
system_influence_scalar : 100.0
alpha : 1.0 # Dirichlet parameter for symmetric Dirichlet on rows on t.p.m for regimes ....
kappa : 0.0 # ...with symmetry-breaking increment to prior to encourage self-transitions. 

### Inference 
num_iters_laplace_em : 100
smart_initialize : True 
num_init_ar_hmms : 1
